server:
  port: 88
  address: 0.0.0.0
spring:
  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: FebsHikariCP
      # 配置默认数据源
      primary: base
      datasource:
        # 数据源-1，名称为 base
        base:
          username: root
          password: 123abc!*
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/gdpt_russia_server_test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8

  data:
    mongodb:
      uri: mongodb://root:Gdpt2022@localhost:27017/russiadb?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false

  redis:
    # Redis数据库索引（默认为 0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
#    password: 123456
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 5000

mybatis-plus:
  configuration:
    cache-enabled: false

websocket:
  service: websocket
  tcpName: ws
#  tcpName: ws

netty:
  port: 12800
  ip: 172.20.10.5
  ssl: true
  enable: false

info:
  download-base-url: http://russia.uprins.com:90/russia/file/
  base-path: /Users/wanghong/IdeaProjects/RussiaPostofficeServerFile/

swagger2:
  host: localhost:88
